-- MySQL Script generated by MySQL Workbench
-- Mon Jun 26 14:43:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema heroku_32efc70736b39b7
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema heroku_32efc70736b39b7
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heroku_32efc70736b39b7` DEFAULT CHARACTER SET utf8 ;
USE `heroku_32efc70736b39b7` ;

-- -----------------------------------------------------
-- Table `heroku_32efc70736b39b7`.`educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_32efc70736b39b7`.`educacion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcione` VARCHAR(500) NULL DEFAULT NULL,
  `nombree` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_32efc70736b39b7`.`experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_32efc70736b39b7`.`experiencia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcione` VARCHAR(500) NULL DEFAULT NULL,
  `nombree` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 144
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_32efc70736b39b7`.`hys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_32efc70736b39b7`.`hys` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `porcentaje` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 274
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_32efc70736b39b7`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_32efc70736b39b7`.`persona` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(1000) NULL DEFAULT NULL,
  `img` VARCHAR(500) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `banner` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_32efc70736b39b7`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_32efc70736b39b7`.`rol` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rol_nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_32efc70736b39b7`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_32efc70736b39b7`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `nombre_usuario` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_puhr3k3l7bj71hb7hk7ktpxn0` (`nombre_usuario` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_32efc70736b39b7`.`usuario_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_32efc70736b39b7`.`usuario_rol` (
  `usuario_id` INT(11) NOT NULL,
  `rol_id` INT(11) NOT NULL,
  PRIMARY KEY (`usuario_id`, `rol_id`),
  INDEX `FK610kvhkwcqk2pxeewur4l7bd1` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `FK610kvhkwcqk2pxeewur4l7bd1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `heroku_32efc70736b39b7`.`rol` (`id`),
  CONSTRAINT `FKbyfgloj439r9wr9smrms9u33r`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `heroku_32efc70736b39b7`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
